# This is a basic workflow to help you get started with Actions

name: Actions Workflow

# on keyword -> defines events that will trigger the workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
      - 'feature/*' # matches with feature/feat-a 
      - 'feature/**' # matches with feature/any/feat-a
      - '!feature/featC'
    # branches-ignore:
       # - develop
    tags:
      - v1.*
    # only run the workflow when there is any changes on JS files  
    paths:  
      - '**.js'
  pull_request:
    branches: [ main ]
    # So some events have something called activity types (for example pull request can have many activity types like opened, closed and so on)
    types: [closed, assigned, opened, reopened]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-github-actions:
    # Use Linux runner to run this job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: List Files
        run: |
          pwd
          ls
      # By default GitHub will not clone our repository into runner's working directory. So in order to that, Github supports checkout action
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files After Checkout
      # $GITHUB_SHA: commit id of the specific commit that triggered this workflow
      # $GITHUB_REPOSITORY: repository name
      # $GITHUB_WORKSPACE : working directory on runner host
      # $GITHUB_REF : the branch that the workflow working with
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          # git clone git@github.com:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple JS Action
        id: greet
        # uses -> reference to a Github Action
        uses: actions/hello-world-javascript-action@v1
        # provides inputs for the action
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
