# This is a basic workflow to help you get started with Actions

name: Context Workflow

# on keyword -> defines events that will trigger the workflow
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - develop

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}' 
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Function 
        run: |
          echo ${{ contains('Hello', 'll') }}
          echo ${{ startsWith('Hello', 'he') }}
          echo ${{ endsWith('Hello', 'lo') }}
          echo ${{ format('Hello {0} {1} {2}', 'Hello', '!', '!') }}
