# This is a basic workflow to help you get started with Actions

name: Shell Commands Workflow

# on keyword -> defines events that will trigger the workflow
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-shell-command:
    # Use Linux runner to run this job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      - name: Runs a single command using the runners shell (the default is bash shell)
        run: echo Hello, world!

      - name: Runs multiple commands using the runners shell (the default is bash shell)
        run: |
          node -v
          npm -v   
          
      - name: Run python commands using python shell
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command: 
    # Use windows runner to run this job
    runs-on: windows-latest
    steps:
      - name: Run windows commands using Powershell
        run: Get-location
      - name: Run windows commands using bash shell
        run: pwd
        shell: bash
                
